services:
  - type: web
    name: gerkobot
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build && ls -la dist
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
